services:
  - type: web
    name: geoai-api
    runtime: python
    buildCommand: npm install && npm run build && pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --workers 2 --timeout 120 --bind 0.0.0.0:$PORT "api.App:app"
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: VITE_MAP_SERVICE_URL
        sync: false
